server:
  port: 8080

app:
  name: To-Do List Manager (DEV режим)
  version: 1.0.0-DEV

logging:
  level:
    com.example.todolist: DEBUG
    org.springframework: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_list_db
    username: ${DB_USERNAME:postgres_user}
    password: ${DB_PASSWORD:changeme}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
