server:
  port: 8080

app:
  name: To-Do List Manager
  version: 1.0.0

logging:
  level:
    com.example.todolist: WARN
    org.springframework: WARN

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
